name: Backend CI

on:
  push:
    branches: [ master ]
    paths:
    - 'server.js'
    - 'Dockerfile'
    - 'config.js'
    - 'package.json'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Build and push to Docker Hub'
      uses: docker/build-push-action@v1
      with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_PASSWORD }}
      repository: masahigo/spa-demo-backend
      tags: latest
