# Basic idea gotten from here: https://github.com/hashicorp/terraform-github-actions

name: Infra CI

on:
  push:
    branches: [ master ]
    paths:
    - 'infra/**'
env:
    tf_version: '0.12.23'
    tf_working_dir: 'infra/terraform'
    az_cli_args: '-var="client_secret=${{ secrets.AZ_CLIENT_SECRET }}" -var="client_id=${{ secrets.AZ_CLIENT_ID }}" -var="tenant_id=${{ secrets.AZ_TENANT_ID }}"'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
          args: '${{ env.az_cli_args }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: false
          args: '-var="linkedin_client_secret=dummyvalue" ${{ env.az_cli_args }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
